### ISSUE TITLE
Invalid Webhook Token

### ISSUE THREAD

**Issue by ROZ-MOFUMOFU-ME** [ROZ-MOFUMOFU-ME/TopazBot#4]
After a certain amount of time has passed since the /play command was used, the webhook token will be disabled and interactivity will not work.
/playコマンドを使用してから一定時間経つとWebhook Tokenが無効になり、インタラクティブが動作しない。

**Comment by ROZ-MOFUMOFU-ME** [comment]
DiscordAPIError: Invalid Webhook Token
    at RequestHandler.execute (/home/root/StreamKey/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/root/StreamKey/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async InteractionWebhook.editMessage (/home/root/StreamKey/node_modules/discord.js/src/structures/Webhook.js:268:15)
    at async CommandInteraction.editReply (/home/root/StreamKey/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:139:21)
    at async play (/home/root/StreamKey/index.js:68:5)
    at async onPlay (/home/root/StreamKey/index.js:231:9) {
  method: 'patch',
  path: '/webhooks/BOT_ID/TOKEN/messages/@original',
  code: 50027,
  httpStatus: 401,
  requestData: {
    json: {
      content: 'Stopped',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}

**Comment by ROZ-MOFUMOFU-ME** [comment]
Webhooks Token have a lifespan of 15 minutes, so I removed the editReply function, and it's working for now, so that's good! But Idk...
